name: wmatarawnavproj
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20200225.2=h33f27b4_0
  - alabaster=0.7.12=py_0
  - argh=0.26.2=py37_1001
  - arrow-cpp=0.17.1=py37h1234567_3_cpu
  - astroid=2.4.1=py37hc8dfbb8_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=19.3.0=py_0
  - autopep8=1.4.4=py_0
  - aws-sdk-cpp=1.7.164=vc14h867dc94_1
  - babel=2.8.0=py_0
  - backcall=0.1.0=py_0
  - bcrypt=3.1.7=py37h8055547_1
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - boost-cpp=1.72.0=h2ba7cf6_1
  - branca=0.4.1=py_0
  - brotli=1.0.7=h33f27b4_1002
  - brotlipy=0.7.0=py37h4ab8f01_1000
  - bzip2=1.0.8=hfa6e2cd_2
  - c-ares=1.15.0=h2fa13f4_1001
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.0=py37ha419a9e_0
  - cfitsio=3.470=he774522_5
  - chardet=3.0.4=py37hc8dfbb8_1006
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=1.4.1=py_0
  - colorama=0.4.3=py_0
  - cryptography=2.9.2=py37h26f1ce3_0
  - curl=7.69.1=h1dcc11c_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20181111=py_0
  - docutils=0.16=py37hc8dfbb8_1
  - entrypoints=0.3=py37hc8dfbb8_1001
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.9=he025d50_2
  - fiona=1.8.13=py37hef9e828_1
  - flake8=3.7.9=py37hc8dfbb8_1
  - folium=0.11.0=py_0
  - freetype=2.10.2=hd328e21_0
  - freexl=1.0.5=hd288d7e_1002
  - future=0.18.2=py37hc8dfbb8_1
  - gdal=3.0.4=py37hd44be9e_9
  - geographiclib=1.50=py_0
  - geopandas=0.7.0=py_1
  - geopy=1.22.0=pyh9f0ad1d_0
  - geos=3.8.1=he025d50_0
  - geotiff=1.5.1=h3d29ae3_10
  - gettext=0.19.8.1=hb01d8f6_1002
  - gflags=2.2.2=he025d50_1002
  - glib=2.64.3=he4de6d7_0
  - glog=0.4.0=h0174b99_3
  - grpc-cpp=1.29.0=h7c6d948_0
  - hdf4=4.2.13=hf8e6fe8_1003
  - hdf5=1.10.6=nompi_ha405e13_100
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.9=py_1
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.6.0=py37hc8dfbb8_0
  - importlib_metadata=1.6.0=0
  - inflection=0.3.1=py_1
  - intel-openmp=2020.0=166
  - intervaltree=3.0.2=py_0
  - ipykernel=5.3.0=py37h5ca1d4c_0
  - ipython=7.15.0=py37hc8dfbb8_0
  - ipython_genutils=0.2.0=py_1
  - isort=4.3.21=py37hc8dfbb8_1
  - jdcal=1.4.1=py_0
  - jedi=0.15.2=py37_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=he774522_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - kealib=1.4.13=h3b59ab9_1
  - keyring=21.2.1=py37hc8dfbb8_0
  - krb5=1.17.1=hdd46e55_0
  - lazy-object-proxy=1.4.3=py37h8055547_2
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libclang=9.0.1=default_hf44288c_0
  - libcurl=7.69.1=h1dcc11c_0
  - libffi=3.2.1=h6538335_1007
  - libgdal=3.0.4=h6f60a84_9
  - libiconv=1.15=hfa6e2cd_1006
  - libkml=1.3.0=h7e985d0_1011
  - liblapack=3.8.0=15_mkl
  - libnetcdf=4.7.4=nompi_h256d12c_104
  - libpng=1.6.37=hfe6a214_1
  - libpq=12.2=hd9aa61d_1
  - libprotobuf=3.11.4=h1a1b453_0
  - libsodium=1.0.17=h2fa13f4_0
  - libspatialindex=1.9.3=he025d50_3
  - libspatialite=4.3.0a=h51df0ed_1038
  - libssh2=1.9.0=h3235a2c_2
  - libtiff=4.1.0=h885aae3_6
  - libwebp-base=1.1.0=hfa6e2cd_3
  - libxml2=2.9.10=h5d81f1c_1
  - lz4-c=1.9.2=h62dcd97_1
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - markupsafe=1.1.1=py37h8055547_1
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py37h8055547_1001
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37hb782905_0
  - more-itertools=8.3.0=py_1
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.6=py_0
  - notebook=6.0.3=py37hc8dfbb8_0
  - numpy=1.18.4=py37hae9e721_0
  - numpydoc=1.0.0=pyh9f0ad1d_0
  - openjpeg=2.3.1=h57dd2e7_3
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1g=he774522_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.4=py37h3bbf574_0
  - pandasql=0.7.3=py37_1
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - paramiko=2.7.1=py37_0
  - parquet-cpp=1.5.1=2
  - parso=0.5.2=py_0
  - pathtools=0.1.2=py_1
  - pcre=8.44=h6538335_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pip=20.0.2=py37_3
  - pluggy=0.13.1=py37hc8dfbb8_1
  - poppler=0.87.0=h0cd1227_1
  - poppler-data=0.4.9=1
  - postgresql=12.2=he14cc48_1
  - proj=7.0.0=haa36216_3
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_0
  - psutil=5.7.0=py37h8055547_1
  - py=1.8.1=py_0
  - pyarrow=0.17.1=py37h1234567_3_cpu
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.20=py_0
  - pydocstyle=5.0.2=py_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.6.1=py_0
  - pylint=2.5.2=py37hc8dfbb8_0
  - pynacl=1.3.0=py37h2fa13f4_1001
  - pyodbc=4.0.30=py37h6538335_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py37h1d8b288_0
  - pyqt=5.12.3=py37h1834ac0_3
  - pyrsistent=0.16.0=py37h8055547_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - pytest=5.4.3=py37hc8dfbb8_0
  - python=3.7.7=h81c818b_4
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.3.4=pyh9f0ad1d_1
  - python-language-server=0.31.10=py37hc8dfbb8_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pywin32=227=py37hfa6e2cd_0
  - pywin32-ctypes=0.2.0=py37hc8dfbb8_1001
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.3.1=py37h8055547_0
  - pyzmq=19.0.1=py37h453f00a_0
  - qdarkstyle=2.8.1=pyh9f0ad1d_0
  - qt=5.12.5=h7ef1ec2_0
  - qtawesome=0.7.2=pyh9f0ad1d_0
  - qtconsole=4.7.4=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - re2=2020.05.01=h33f27b4_1
  - requests=2.23.0=pyh8c360ce_2
  - rope=0.17.0=pyh9f0ad1d_0
  - rtree=0.9.4=py37h804a536_1
  - scipy=1.4.1=py37h9439919_0
  - send2trash=1.5.0=py_0
  - setuptools=46.4.0=py37_0
  - shapely=1.7.0=py37he1cf020_3
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=he025d50_1
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.1.0=py_0
  - sphinx=3.0.4=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - spyder=4.1.3=py37hc8dfbb8_0
  - spyder-kernels=1.9.1=py37hc8dfbb8_0
  - sqlalchemy=1.3.17=py37h4ab8f01_0
  - sqlite=3.31.1=h2a8f88b_1
  - tbb=2020.1=he980bc4_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - thrift-cpp=0.13.0=h1907cbf_2
  - tiledb=1.7.7=h0b90766_3
  - tk=8.6.10=hfa6e2cd_0
  - toml=0.10.1=pyh9f0ad1d_0
  - tornado=6.0.4=py37hfa6e2cd_0
  - traitlets=4.3.3=py37hc8dfbb8_1
  - typed-ast=1.4.1=py37hfa6e2cd_0
  - ujson=1.35=py37h63f7a3c_1002
  - urllib3=1.25.9=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_2
  - watchdog=0.10.2=py37_0
  - wcwidth=0.2.2=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.11.2=py37h8055547_0
  - xerces-c=3.2.2=h6538335_1004
  - xz=5.2.5=h2fa13f4_0
  - yaml=0.2.4=he774522_0
  - yapf=0.29.0=py_0
  - zeromq=4.3.2=h6538335_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.4=h9f78265_3
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
prefix: C:\Users\WylieTimmerman\.conda\envs\wmatarawnavproj

